execute:
  freeze: auto
project:
  resources:
    - "Resources"
    - "style_site.scss"
  type: website
  output-dir: public
website:
  title: "A kPCA illustration"
  description: "A kPCA illustration"
  navbar:
    left:
      - href: kPCA_v_SVD.qmd
        text: kPCA v.s. SVD
    right:
      - href: https://alexandredabyseesaram.github.io/
        text: Alexandre Daby-Seesaram's homepage
format:
  pdf: default
  html:
    theme:
      light: [flatly,style_site.scss]
      dark: darkly
    css: styles.css
    toc: true



