execute:
  freeze: auto
project:
  resources:
    - "Resources"
  type: website
  output-dir: public
website:
  title: "A kPCA illustration"
  description: "A kPCA illustration"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: kPCA_v_SVD.qmd
        text: kPCA v.s. SVD
format:
  pdf: default
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



