execute:
  freeze: auto
project:
  resources:
    - "Resources"
  type: website
  output-dir: public
website:
  title: "A static jupyter's book website"
  description: "SVD and autoencoder"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: Autoencoder.qmd
        text: Autoencoder
      - href: SVD.qmd
        text: SVD
      - href: SpacePartition_Separability.ipynb
        text: Direct SVD_jupyter
      - href: SP.qmd
        text: SVD_jupyter
format:
  pdf: default
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



